# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  - name: Software
    url: software/
    weight: 30
  - name: Research
    url: research/
    weight: 40
  - name: Rublication
    url: publication/
    weight: 50
  - name: Blog
    url: blog/
    weight: 60
  - name: News
    url: news/
    weight: 70
  - name: Examples
    url: examples/
    weight: 80
